version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: ghup
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/nexthink-oss/ghup/cmd.version={{.Version}}
        -X github.com/nexthink-oss/ghup/cmd.commit={{.ShortCommit}}
        -X github.com/nexthink-oss/ghup/cmd.date={{.Date}}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  version_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: isometry
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    description: A GitHub API client for managing tags and repository content from third-party automation systems
    homepage: https://just.breathe.io/project/ghup/
    test: |
      system "#{bin}/ghup --help"
    install: |
      bin.install "ghup"
